### ISSUE TITLE
Yii2 version?

### ISSUE THREAD

**Issue by FedericoBenedetti1976** [bizley-code/Yii-CookieMonster#1]
Question: Hi, is there a way to adjust this extension with Yii2?
Thanks

**Comment by bizley** [comment]
It's quite simple extension so it shouldn't be a problem. I think I'll prepare Yii 2 version this week.

**Comment by bizley** [comment]
You can find Yii 2 version at https://github.com/bizley-code/yii2-cookiemonster

**Comment by FedericoBenedetti1976** [comment]
thank you very much!

---

_Da:_ Bizley mailto:%3Ca%3Enotifications@github.com%3C/a%3E
_Inviato:_ Venerdì, Maggio 29, 2015 9:32PM
_A:_ Bizley-code/yii-cookiemonster 
mailto:%3Ca%3EYii-CookieMonster@noreply.github.com%3C/a%3E
_Cc:_ Account Vari Aurales mailto:%3Ca%3Eaccount@aurales.it%3C/a%3E
_Oggetto:_ Re: [Yii-CookieMonster] Yii2 version? (#1)

You can find Yii 2 version at 
https://github.com/bizley-code/yii2-cookiemonster
